FROM elixir:1.5.1
ENV DEBIAN_FRONTEND=noninteractive
EXPOSE 8000
ENV PORT=8000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/bash
WORKDIR /app
COPY ./phoenix_deploy.tar.gz ./
RUN tar xfz phoenix_deploy.tar.gz
ENTRYPOINT ["bin/phoenix_deploy"]